# Generated by Django 4.2.2 on 2024-05-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('EpicName', models.CharField(default=None, max_length=20)),
                ('Epic_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('guide', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('sprint', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sprint_goal', models.TextField(default='okay', null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueName', models.CharField(max_length=30)),
                ('IssueId', models.CharField(max_length=20, unique=True)),
                ('is_addedTosprint', models.BooleanField(max_length=5)),
                ('status', models.CharField(max_length=30)),
                ('assignee', models.CharField(max_length=30)),
                ('assigned_by', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=30)),
                ('assigned_epic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djapp.epic')),
                ('projectId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djapp.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djapp.sprint')),
            ],
        ),
    ]
