# Generated by Django 4.2.5 on 2024-04-12 04:06

from django.db import migrations, models
import djapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=djapp.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
