# Generated by Django 4.0.3 on 2024-05-02 08:32

from django.db import migrations, models
import djapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='room',
        ),
        migrations.AddField(
            model_name='team',
            name='useremail',
            field=models.EmailField(default='abc@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=djapp.models.generate_user_id, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
