# Generated by Django 4.0.3 on 2024-05-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_epic_delete_room_team_useremail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='teamlead_mail',
            field=models.EmailField(default='abc@gmail.com', max_length=254, null=True),
        ),
    ]
