# Generated by Django 4.2.2 on 2024-05-02 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0004_sprint_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='projectId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djapp.project'),
        ),
    ]
