# Generated by Django 4.2.2 on 2024-05-03 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0005_backlog_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djapp.project'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='sprint_goal',
            field=models.TextField(default='okay', null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='sprint',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
    ]
