# Generated by Django 5.0.4 on 2024-04-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='React',
            new_name='employeeData',
        ),
    ]
