# Generated by Django 5.0.4 on 2024-04-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_react_employeedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlogName', models.CharField(max_length=30)),
                ('backlogId', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='employeeData',
        ),
    ]
